services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-resume-analyzer-api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    # For future integrations like redis or db, network can be setup here.
    networks:
      - resume-network

networks:
  resume-network:
    driver: bridge
